### ISSUE TITLE
Convert HTML to PDF?

### ISSUE THREAD

**Issue by kirkins** [lob/lob-templates#3]
I want to modify the HTML for the templates but I can only upload PDF format to Lob.

Can you add instructions for generating a PDF from the template?

**Comment by kirkins** [comment]
never mind I guess templates have to be uploaded from a different page

**Comment by kirkins** [comment]
I'm still interested in finding a better way to do this.

I want to render postcards on my own server and just send the end result as an image to Lob.

I found `phantomjs` works if you use the[ rasterize.js file](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) they have in their examples:

    phantomjs ~/bin/rasterize.js front.html testing.pdf "6.25in*4.24in"

It somewhat works but the sizing is all off. I never end up with results as good as the examples included here.

If anyone has a better way to render the HTML to image or pdf, I'm very interested.

**Comment by ami** [comment]
@kirkins When creating postcards with Lob, you can simply send us HTML and we will take care of the rendering (much better than Phantom.js). If you need help doing that, please submit a ticket to support@lob.com. Will be closing this issue as it is unrelated to this repo (which is simply a repo of templates for use with Lob).
